### ISSUE TITLE
gists.map is not a function

### ISSUE THREAD

**Issue by XianwuLin** [dbankier/vscode-gist#5]
![image](https://cloud.githubusercontent.com/assets/5524532/15495017/2651c580-21c0-11e6-93d9-150ee265eea2.png)

then:

![image](https://cloud.githubusercontent.com/assets/5524532/15494980/03de7304-21c0-11e6-8293-08696c80dcde.png)

**Comment by khaosdoctor** [comment]
Updating the issue here.

I'm also having this problem, here's the picture:

![image](https://cloud.githubusercontent.com/assets/3200560/18608502/5ca680ce-7cc1-11e6-9927-72395451a889.png)

It has something to do with the newest vscode version, because I opened a gist a few moments back before updating and it worked fine... After the update things started going sideways.

**Comment by khaosdoctor** [comment]
No, it does not have anything to do with versions. I just regenerate a new token and updated it to the settings. Then it magically worked

**Comment by kenhowardpdx** [comment]
This is fixed in master. I'll update here when published to the Marketplace.
